local M = {}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hl("@keyword", { fg = "#cba6f7", bold = true })
hl("@function", { fg = "#89b4fa" })
hl("@function.builtin", { fg = "#89b4fa", italic = true })
hl("@function.macro", { fg = "#89b4fa", bold = true })
hl("@type", { fg = "#f38ba8" })
hl("@type.builtin", { fg = "#f38ba8", italic = true })
hl("@type.definition", { fg = "#f38ba8", underline = true })
hl("@variable", { fg = "#cdd6f4" })
hl("@variable.builtin", { fg = "#f38ba8" })
hl("@string", { fg = "#a6e3a1" })
hl("@string.escape", { fg = "#f38ba8", bold = true })
hl("@string.regex", { fg = "#a6e3a1", italic = true })
hl("@number", { fg = "#fab387" })
hl("@number.float", { fg = "#fab387" })
hl("@boolean", { fg = "#fab387" })
hl("@comment", { fg = "#6c7086", italic = true })
hl("@comment.doc", { fg = "#6c7086", italic = true })
hl("@operator", { fg = "#89dceb" })
hl("@punctuation", { fg = "#94e2d5" })
hl("@punctuation.bracket", { fg = "#94e2d5" })
hl("@punctuation.delimiter", { fg = "#94e2d5" })
hl("@constant", { fg = "#fab387" })
hl("@constant.builtin", { fg = "#fab387", bold = true })
hl("@constant.macro", { fg = "#fab387", underline = true })
hl("@attribute", { fg = "#f9e2af" })
hl("@attribute.builtin", { fg = "#f9e2af", italic = true })
hl("@field", { fg = "#cba6f7" })
hl("@field.property", { fg = "#cba6f7" })
hl("@parameter", { fg = "#f38ba8", italic = true })
hl("@parameter.reference", { fg = "#cdd6f4" })
hl("@namespace", { fg = "#89b4fa" })
hl("@module", { fg = "#89b4fa" })
hl("@label", { fg = "#89dceb" })
hl("@tag", { fg = "#f38ba8" })
hl("@tag.delimiter", { fg = "#94e2d5" })
hl("@tag.attribute", { fg = "#f9e2af" })
hl("@regex", { fg = "#a6e3a1" })
hl("@escape", { fg = "#f38ba8", bold = true })
hl("@special", { fg = "#fab387" })
hl("@special.char", { fg = "#fab387" })
hl("@special.url", { fg = "#89dceb", underline = true })

hl("@text", { fg = "#cdd6f4" })
hl("@text.strong", { fg = "#cdd6f4", bold = true })
hl("@text.emphasis", { fg = "#cdd6f4", italic = true })
hl("@text.underline", { fg = "#cdd6f4", underline = true })
hl("@text.strike", { fg = "#6c7086", strikethrough = true })
hl("@text.title", { fg = "#89b4fa", bold = true })
hl("@text.title.1", { fg = "#89b4fa", bold = true })
hl("@text.title.2", { fg = "#cba6f7", bold = true })
hl("@text.title.3", { fg = "#f38ba8", bold = true })
hl("@text.title.4", { fg = "#f9e2af", bold = true })
hl("@text.title.5", { fg = "#fab387", bold = true })
hl("@text.uri", { fg = "#89dceb", underline = true })
hl("@text.literal", { fg = "#a6e3a1" })
hl("@text.math", { fg = "#fab387" })
hl("@text.note", { fg = "#89b4fa", italic = true })
hl("@text.warning", { fg = "#f9e2af", bold = true })
hl("@text.danger", { fg = "#f38ba8", bold = true })
hl("@text.diff.add", { fg = "#a6e3a1" })
hl("@text.diff.delete", { fg = "#f38ba8" })

hl("@symbol", { fg = "#cba6f7" })
hl("@symbol.bracket", { fg = "#94e2d5" })
hl("@symbol.inner", { fg = "#89dceb" })
hl("@symbol.outer", { fg = "#89dceb", bold = true })

hl("TSNone", { fg = "#cdd6f4" })

hl("StatuslineGit", { fg = "#a6e3a1", bg = "#45475a" })
hl("StatuslineGitDirty", { fg = "#f38ba8", bg = "#45475a" })
hl("StatuslineMode", { fg = "#cdd6f4", bg = "#584469", bold = true })
hl("StatuslineReadonly", { fg = "#f9e2af", bg = "#45475a" })
hl("StatuslineInfo", { fg = "#89b4fa", bg = "#45475a" })
hl("StatuslineSubtle", { fg = "#bac2de", bg = "#45475a", bold = true })
hl("StatuslineSearch", { fg = "#cba6f7", bg = "#45475a" })

-- Bufferline / tabline colors (used by statusline.bufferline())
hl("TabLine", { fg = "#cdd6f4", bg = "#1e1e2e" })
hl("TabLineSel", { fg = "#89b4fa", bg = "#313244", bold = true })
hl("TabLineFill", { fg = "#585b70", bg = "#1e1e2e" })
hl("TabLineMod", { fg = "#f38ba8", bg = "#1e1e2e", bold = true })

M.hl = hl

return M